### ISSUE TITLE
serveo_1  | 2021/04/09 16:42:38 http: proxy error: No tunnel for 34.x.x.x

### ISSUE THREAD

**Issue by khairi96** [taichunmin/docker-serveo-server#10]
I am using a google cloud server as my **serveo-server**, I followed the instructions, set up Cloudflare DNS, and everything worked fine, however, My app running on my local machine on **localhost:8000**  when I use 
`ssh -R test.abc.com:443:localhost:8000 abc.com -p 2222 ` from my local machine it doesn't do anything, and halts.

this the output of `docker-compose logs` from the server:
Attaching to docker-serveo-server_serveo_1
serveo_1  | 2021/04/09 16:39:06 Listening on :22...
serveo_1  | 2021/04/09 16:42:38 http: proxy error: No tunnel for 34.x.x.x 

 
Please, Can anyone tell me what's wrong? 
Thank you!

**Comment by taichunmin** [comment]
Can you try to exclude domain suffix? `ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=no -R test:80:localhost:22880 -p 2222 abc.com`

**Comment by khairi96** [comment]
Thank you for your help. 

I tried it and didn't work, the same problem it halts on the local machine, and then returns:

ssh: connect to host abc.com port 22: Network is unreachable


However, when I checked server docker compose log:

Attaching to docker-serveo-server_serveo_1
serveo_1  | 2021/04/09 16:39:06 Listening on :22...
serveo_1  | 2021/04/09 16:42:38 http: proxy error: No tunnel for 34.x.x.x
serveo_1  | 2021/04/09 17:03:23 http: proxy error: No tunnel for 34.x.x.x
serveo_1  | 2021/04/09 17:18:10 MuxListener error peeking into conn: read tcp 172.x.x.x:443->162.x.x.x:45736: read: connection reset by peer
serveo_1  | 2021/04/09 17:18:10 http: TLS handshake error from 162.x.x.x:45586: tls: no certificate available
serveo_1  | 2021/04/09 17:18:11 http: TLS handshake error from 162.x.x.x:58040: tls: first record does not look like a TLS handshake
serveo_1  | 2021/04/09 17:18:12 http: TLS handshake error from 162.x.x.x:37618: tls: no certificate available
serveo_1  | 2021/04/10 15:11:23 Listening on :22... 


Not sure why?

**Comment by taichunmin** [comment]
You need to change the domain in the command.

**Comment by khairi96** [comment]
I changed the domain as you suggested, and the port to `-p 22`
Thank you once again @taichunmin !
