### ISSUE TITLE
Port forwarding request rejected: port forwarding limit reached

### ISSUE THREAD

**Issue by Brandimic0** [taichunmin/docker-serveo-server#12]
I have multiple active connection, whenever i want to add more it gives 

Port forwarding request rejected: port forwarding limit reached

it's selfhosted

check logs

![Screenshot 2024-04-02 at 2 34 07 PM](https://github.com/taichunmin/docker-serveo-server/assets/87997719/492f896a-0467-4920-a83c-ed19625045bf)

**Comment by taichunmin** [comment]
Sorry, the limitation comes from the original program, please ask [serveo](https://serveo.net/)
